import WorkflowTemplate from '../models/workflowTemplateModel';

export const seedCondominiumTransferTemplate = async () => {
  const name = 'Condominium Transfer';
  const version = 1;

  const template = {
    name,
    matterType: 'Condominium Transfer',
    caseType: 'Transactional Cases',
    version,
    active: true,

    stages: [
      { key: 'pre_sale', order: 1, title: 'Pre-Sale Preparation & Documentation' },
      { key: 'valuation_marketing', order: 2, title: 'Valuation, Marketing & Negotiation' },
      { key: 'preliminary_sale', order: 3, title: 'Preliminary Sale Agreement & Legal Formalities' },
      { key: 'notarization', order: 4, title: 'Notarization & Execution of Deed of Sale' },
      { key: 'land_registry', order: 5, title: 'Land Registry - Registration of Transfer' },
      { key: 'post_transfer', order: 6, title: 'Post-Transfer Obligations & Compliance' },
    ],

    steps: [
      {
        key: 'CONDO_1_INTAKE',
        order: 1,
        stageKey: 'pre_sale',
        title: 'Client Intake & Initial Assessment',
        actions: ['Receive inquiry from seller and confirm buyer if identified', 'Confirm seller is registered unit owner', 'Verify condominium association is registered', 'Collect names, nationality, contacts and unit description', 'Schedule formal consultation'],
        outputs: [
          { key: 'client_intake', name: 'Client intake form completed', required: true, category: 'Intake' },
          { key: 'seller_owner_confirmed', name: 'Seller confirmed as legal unit owner', required: true, category: 'Land Registry' },
          { key: 'consultation_confirmed', name: 'Consultation appointment confirmed', required: true, category: 'Intake' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 13 and 27; RBA Regulation Art. 7' }],
        fee: { type: 'included', text: 'Free' },
        sla: { unit: 'hours', min: 0, max: 24, text: '24 hours' },
      },
      {
        key: 'CONDO_2_UNIT_OWNERSHIP',
        order: 2,
        stageKey: 'pre_sale',
        title: 'Verification of Unit Ownership',
        actions: ['Access RLMUA / RDB land registry', "Confirm seller's name matches registered owner", 'Check encumbrances, mortgages, caveats or disputes', 'Verify unit co-share participation percentage', 'Confirm unit boundaries as surveyed and registered'],
        outputs: [
          { key: 'ownership_verified', name: 'Ownership verified', required: true, category: 'Land Registry' },
          { key: 'no_encumbrances', name: 'No encumbrances confirmed', required: true, category: 'Due Diligence' },
          { key: 'coshare_confirmed', name: 'Co-share percentage confirmed', required: true, category: 'Condominium' },
          { key: 'boundaries_confirmed', name: 'Unit boundaries confirmed', required: true, category: 'Condominium' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 20, 26, 27 and 28' }],
        fee: { type: 'included', text: 'Free' },
        sla: { unit: 'hours', min: 0, max: 24, text: '24 hours' },
      },
      {
        key: 'CONDO_3_DOCUMENTS',
        order: 3,
        stageKey: 'pre_sale',
        title: 'Collection of Condominium Documents',
        actions: ['Obtain Declaration of Division / Master Deed', 'Collect association Articles of Association', 'Obtain by-laws and transfer rules', 'Request minutes of owners meetings for last 3 years', 'Obtain maintenance reserve statement', 'Obtain no-outstanding-common-charges clearance'],
        outputs: [
          { key: 'documentation_package', name: 'Full documentation package assembled', required: true, category: 'Documents' },
          { key: 'clearance_certificate', name: 'Clearance certificate obtained', required: true, category: 'Condominium' },
          { key: 'arrears_clearance', name: 'Seller confirmed free of arrears', required: true, category: 'Condominium' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 6, 11 and 22' }],
        fee: { type: 'text', text: 'Variable association admin fees' },
        sla: { unit: 'days', min: 1, max: 3, text: '24-72 hours depending on document' },
      },
      {
        key: 'CONDO_4_POA',
        order: 4,
        stageKey: 'pre_sale',
        title: 'Power of Attorney (If Applicable)',
        actions: ['Confirm seller or buyer is outside Rwanda', 'Client executes POA granting authority to firm', 'Ensure POA is notarized and legalized/apostilled', 'Receive original POA before commencing action'],
        outputs: [
          { key: 'original_poa', name: 'Original POA received and filed', required: false, category: 'Representation' },
          { key: 'firm_authority', name: "Firm authorized to act on client's behalf", required: false, category: 'Representation' },
        ],
        legalBasis: [{ text: 'Civil Code, Arts. 1 and 3; RBA Regulation Art. 4' }],
        fee: { type: 'text', text: 'POA handling fees as agreed' },
        sla: { unit: 'days', min: 0, max: 3, text: '72 hours' },
      },
      {
        key: 'CONDO_5_VALUATION',
        order: 5,
        stageKey: 'valuation_marketing',
        title: 'Property Valuation',
        actions: ['Engage government-recognized property valuer', 'Value unit area, floor, co-share percentage and building condition', 'Review recent comparable sales', 'Agree listing price with seller', 'Prepare unit description for marketing'],
        outputs: [
          { key: 'valuation_report', name: 'Certified property valuation report', required: true, category: 'Valuation' },
          { key: 'listing_price', name: 'Agreed listing price confirmed by seller', required: true, category: 'Valuation' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Art. 26(2); Ministerial Order on land valuation' }],
        fee: { type: 'text', text: "Variable - RWF 50,000-200,000+ valuer's fees" },
        sla: { unit: 'days', min: 2, max: 3, text: '48-72 hours' },
      },
      {
        key: 'CONDO_6_MARKETING',
        order: 6,
        stageKey: 'valuation_marketing',
        title: 'Marketing & Viewings',
        actions: ['List unit on property platforms', 'Prepare marketing materials', 'Coordinate viewings', 'Provide buyers with by-laws, minutes and financials', 'Confirm viewings comply with building rules'],
        outputs: [
          { key: 'unit_listed', name: 'Unit listed and actively marketed', required: false, category: 'Marketing' },
          { key: 'viewings_conducted', name: 'Viewings conducted', required: false, category: 'Marketing' },
          { key: 'buyer_disclosures', name: 'Prospective buyers informed of obligations', required: false, category: 'Disclosure' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 11 and 17' }],
        fee: { type: 'text', text: 'Variable marketing costs' },
        sla: { unit: 'days', min: 1, max: 3, text: '24-72 hours' },
      },
      {
        key: 'CONDO_7_HEADS',
        order: 7,
        stageKey: 'valuation_marketing',
        title: 'Offer to Purchase & Heads of Terms',
        actions: ['Receive buyer formal written offer', 'Negotiate price and conditions', 'Confirm buyer reviewed condominium documentation', 'Issue Heads of Terms / Letter of Intent', 'Confirm agreement on outstanding debts'],
        outputs: [
          { key: 'accepted_offer', name: 'Accepted offer confirmed in writing', required: true, category: 'Offer' },
          { key: 'heads_terms', name: 'Heads of Terms signed by both parties', required: true, category: 'Offer' },
          { key: 'debts_confirmed', name: 'Outstanding debts confirmed', required: true, category: 'Condominium' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Art. 22; RBA Regulation Art. 4' }],
        fee: { type: 'included', text: 'Free' },
        sla: { unit: 'days', min: 1, max: 2, text: '24-48 hours' },
      },
      {
        key: 'CONDO_8_TIN_ID',
        order: 8,
        stageKey: 'preliminary_sale',
        title: 'TIN & Identity Document Verification',
        actions: ['Confirm buyer has valid TIN registered with RRA', 'Collect certified IDs or passports', 'Verify identity documents are valid and not expired', "Confirm buyer's TIN matches identity documentation"],
        outputs: [
          { key: 'buyer_tin', name: 'Verified TIN for buyer', required: true, category: 'Tax' },
          { key: 'valid_ids', name: 'Valid identity documents confirmed for both parties', required: true, category: 'Identity' },
        ],
        legalBasis: [{ text: 'RRA Regulations; RBA Regulation Art. 7' }],
        fee: { type: 'included', text: 'Free - TIN registration at RRA' },
        sla: { unit: 'days', min: 1, max: 2, text: '24-48 hours' },
      },
      {
        key: 'CONDO_9_PSA',
        order: 9,
        stageKey: 'preliminary_sale',
        title: 'Preliminary Sale Agreement',
        actions: ['Draft PSA with unit ID, co-share, price, payment terms and conditions', 'Include common elements in sale', 'Address transfer of former owner rights and obligations', 'Obtain signatures', 'Confirm buyer deposit'],
        outputs: [
          { key: 'signed_psa', name: 'Signed Preliminary Sale Agreement', required: true, category: 'Contract' },
          { key: 'deposit_receipt', name: 'Deposit received and receipted', required: true, category: 'Payment' },
          { key: 'parties_bound', name: 'Both parties bound to proceed', required: true, category: 'Contract' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 18, 19 and 22; Bareme RBA Scale II' }],
        fee: { type: 'text', text: 'Bareme RBA Scale II: 4% first RWF 50M; 1.5% RWF 50M-1B; 1.25% next band; plus RWF 30,000 opening fee' },
        sla: { unit: 'days', min: 1, max: 2, text: '24-48 hours' },
      },
      {
        key: 'CONDO_10_BUYER_DD',
        order: 10,
        stageKey: 'preliminary_sale',
        title: 'Due Diligence Period (Buyer)',
        actions: ['Buyer reviews by-laws, minutes, financial records and reserves', 'Verify no pending special assessments or major repair works', 'Confirm co-ownership obligations', 'Buyer arranges financing if applicable', 'Resolve issues before final deed'],
        outputs: [
          { key: 'buyer_dd_completed', name: 'Due diligence completed by buyer', required: true, category: 'Due Diligence' },
          { key: 'issues_resolved', name: 'No material issues outstanding', required: true, category: 'Due Diligence' },
          { key: 'readiness_confirmation', name: 'Buyer confirms readiness to proceed', required: true, category: 'Due Diligence' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 6 and 22; RBA Regulation Arts. 4 and 10' }],
        fee: { type: 'included', text: "Free - buyer's own review" },
        sla: { unit: 'days', min: 2, max: 5, text: '2-5 days' },
      },
      {
        key: 'CONDO_11_FINAL_DEED',
        order: 11,
        stageKey: 'notarization',
        title: 'Notary Appointment & Final Deed Preparation',
        actions: ['Engage notary public', 'Notary conducts final title and encumbrance verification', 'Confirm association clearance remains current', 'Draft final Deed of Sale', 'Both parties review final deed before execution'],
        outputs: [
          { key: 'final_deed_draft', name: 'Final Deed of Sale drafted', required: true, category: 'Notary' },
          { key: 'party_approval', name: 'Both parties approve', required: true, category: 'Notary' },
          { key: 'title_clear', name: 'Notary confirms title clear', required: true, category: 'Notary' },
        ],
        legalBasis: [{ text: 'Rwandan notarization law; Law No. 15/2010, Arts. 27 and 28' }],
        fee: { type: 'text', text: 'RWF 50,000-150,000 notary fees; RBA scale on transaction value may apply' },
        sla: { unit: 'hours', min: 0, max: 24, text: '24 hours' },
      },
      {
        key: 'CONDO_12_EXECUTION',
        order: 12,
        stageKey: 'notarization',
        title: 'Execution of the Deed of Sale',
        actions: ['Parties appear before notary or POA holder', 'Seller and buyer sign final deed', 'Balance of purchase price paid to seller', 'Notary certifies deed and affixes seal', 'Notary provides certified copies'],
        outputs: [
          { key: 'executed_deed', name: 'Executed and notarized Deed of Sale', required: true, category: 'Notary' },
          { key: 'balance_paid', name: 'Balance of purchase price received by seller', required: true, category: 'Payment' },
          { key: 'certified_copies', name: 'Certified copies issued to both parties', required: true, category: 'Notary' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Art. 22; Notarial Law of Rwanda; RBA Regulation Art. 15' }],
        fee: { type: 'included', text: 'Included in notary fees' },
        sla: { unit: 'hours', min: 0, max: 24, text: '24 hours' },
      },
      {
        key: 'CONDO_13_TAX_CLEARANCE',
        order: 13,
        stageKey: 'notarization',
        title: 'Tax Clearance & Transfer Taxes',
        actions: ['Obtain tax clearance certificates from RRA', 'Calculate and pay Capital Gains Tax if applicable', 'Pay Transfer Tax / Registration Tax', 'Retain all tax payment receipts', 'Confirm outstanding property taxes are settled'],
        outputs: [
          { key: 'taxes_paid', name: 'All applicable taxes paid', required: true, category: 'Tax' },
          { key: 'tax_clearance', name: 'Tax clearance certificates obtained', required: true, category: 'Tax' },
          { key: 'payment_receipts', name: 'Payment receipts retained for registration', required: true, category: 'Tax' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 25 and 29; RRA Income Tax Law' }],
        fee: { type: 'text', text: 'Variable CGT and transfer tax per applicable rates; registration fee per Ministerial Order' },
        sla: { unit: 'days', min: 1, max: 3, text: '24-72 hours' },
      },
      {
        key: 'CONDO_14_REGISTRY_SUBMISSION',
        order: 14,
        stageKey: 'land_registry',
        title: 'Submission to Land Registry',
        actions: ['Submit executed Deed of Sale and supporting documents to Registrar', 'Registrar verifies boundaries, co-share and title details', 'Registrar checks caveats or inscriptions', 'Pay registration fees', 'Obtain submission reference and acknowledgement receipt'],
        outputs: [
          { key: 'registry_submission', name: 'Application submitted to Land Registry', required: true, category: 'Land Registry' },
          { key: 'submission_ref', name: 'Submission reference number obtained', required: true, category: 'Land Registry' },
          { key: 'ack_receipt', name: 'Acknowledgement receipt issued', required: true, category: 'Land Registry' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 27, 28 and 29' }],
        fee: { type: 'text', text: 'Per Ministerial Order - land registration fees' },
        sla: { unit: 'hours', min: 0, max: 24, text: '24 hours' },
      },
      {
        key: 'CONDO_15_NEW_TITLE',
        order: 15,
        stageKey: 'land_registry',
        title: 'Issuance of New Certificate of Title',
        actions: ['Registrar updates condominium register in buyer name', 'New Condominium Certificate of Title issued to buyer', 'Old Certificate of Title cancelled and archived', 'Registrar issues transfer completion notification', 'Buyer collects new Certificate of Title'],
        outputs: [
          { key: 'new_title', name: "New Condominium Certificate of Title issued in buyer's name", required: true, category: 'Land Registry' },
          { key: 'old_title_cancelled', name: 'Old Certificate of Title cancelled', required: true, category: 'Land Registry' },
          { key: 'register_updated', name: 'Land register updated', required: true, category: 'Land Registry' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 26, 27 and 30' }],
        fee: { type: 'included', text: 'Included in registration fees' },
        sla: { unit: 'days', min: 2, max: 3, text: '48-72 hours' },
      },
      {
        key: 'CONDO_16_ASSOCIATION',
        order: 16,
        stageKey: 'post_transfer',
        title: 'Notification of Condominium Association',
        actions: ['Notify association or management company of ownership change', 'Submit new Certificate of Title to association', 'Confirm buyer membership begins upon registration', 'Update association records', 'Confirm transfer of association membership'],
        outputs: [
          { key: 'association_notified', name: 'Association formally notified', required: true, category: 'Condominium' },
          { key: 'buyer_member', name: 'Buyer registered as association member', required: true, category: 'Condominium' },
          { key: 'records_updated', name: 'Association records updated', required: true, category: 'Condominium' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 11, 13 and 22' }],
        fee: { type: 'included', text: 'Free' },
        sla: { unit: 'days', min: 1, max: 2, text: '24-48 hours' },
      },
      {
        key: 'CONDO_17_HANDOVER',
        order: 17,
        stageKey: 'post_transfer',
        title: 'Physical Handover of Unit',
        actions: ['Seller vacates unit on agreed handover date', 'Transfer keys, access cards and parking passes', 'Conduct joint inspection', 'Document unit condition at handover', 'Seller provides technical documents and utility information', 'Confirm utility accounts transferred to buyer'],
        outputs: [
          { key: 'unit_handover', name: 'Unit physically handed over to buyer', required: true, category: 'Handover' },
          { key: 'keys_transferred', name: 'All keys and access cards transferred', required: true, category: 'Handover' },
          { key: 'condition_report', name: 'Handover condition report signed', required: true, category: 'Handover' },
          { key: 'utilities_transferred', name: 'Utility accounts transferred', required: false, category: 'Handover' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 22 and 23; general contract law' }],
        fee: { type: 'included', text: 'Free' },
        sla: { unit: 'days', min: 0, max: 2, text: 'On agreed handover date; supporting items within 24-48 hours' },
      },
      {
        key: 'CONDO_18_INSURANCE',
        order: 18,
        stageKey: 'post_transfer',
        title: 'Insurance & Ongoing Obligations',
        actions: ['Buyer obtains unit insurance', 'Confirm association insurance for condominium property', 'Buyer begins contributing to common charges', 'Buyer assumes rights and obligations of former owner', 'Buyer complies with association rules and by-laws'],
        outputs: [
          { key: 'unit_insurance', name: "Unit insurance policy in buyer's name", required: false, category: 'Insurance' },
          { key: 'common_charges', name: 'Buyer enrolled in common charges billing', required: false, category: 'Condominium' },
          { key: 'association_compliance', name: 'Buyer compliant with association obligations', required: false, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 14, 20, 22 and 23' }],
        fee: { type: 'text', text: 'Variable insurance premiums and ongoing common charges' },
        sla: { unit: 'days', min: 1, max: 3, text: '72 hours' },
      },
      {
        key: 'CONDO_19_DISPUTE',
        order: 19,
        stageKey: 'post_transfer',
        title: 'Dispute Resolution & Error Correction',
        actions: ['Review Land Registry or association rejection reason', 'Correct document mismatch, unpaid charges or boundary disputes and resubmit', 'Lodge complaint with RLMUA/RDB or Rwanda National Police for fraud or ownership disputes', 'Escalate legal disputes to Primary Court or High Court'],
        outputs: [
          { key: 'rejection_resolved', name: 'Rejection resolved and transfer completed', required: false, category: 'Dispute' },
          { key: 'corrected_submission', name: 'Corrected submission acknowledgement', required: false, category: 'Dispute' },
          { key: 'dispute_reference', name: 'Dispute complaint reference (if applicable)', required: false, category: 'Dispute' },
        ],
        legalBasis: [{ text: 'Law No. 15/2010, Arts. 27 and 28; Organic Law on Courts; RBA Regulation Art. 20' }],
        fee: { type: 'text', text: 'Free admin correction; variable legal action if required' },
        sla: { unit: 'days', min: 2, max: 4, text: '2-4 days depending on issue' },
      },
    ],
  };

  await WorkflowTemplate.updateMany(
    { name, version: { $lt: version } },
    { $set: { active: false } }
  );

  return WorkflowTemplate.findOneAndUpdate(
    { name, version },
    { $set: template },
    { returnDocument: 'after', upsert: true, setDefaultsOnInsert: true }
  );
};
