import WorkflowTemplate from '../models/workflowTemplateModel';

export const seedDueDiligenceTemplate = async () => {
  const name = 'Due Diligence (Land)';
  const version = 1;

  const exists = await WorkflowTemplate.findOne({ name, version });
  if (exists) return exists;

  return WorkflowTemplate.create({
    name,
    matterType: 'Due Diligence (Land)',
    caseType: 'Transactional Cases',
    version,
    active: true,

    stages: [
      { key: 'onboarding', order: 1, title: 'Client Onboarding & Consultation' },
      { key: 'initial_review', order: 2, title: 'Initial Review & Legal Assessment' },
      { key: 'basic_dd', order: 3, title: 'Basic Due Diligence' },
      { key: 'contract_basic', order: 4, title: 'Contract Preparation & Advisory (Basic)' },
      { key: 'comprehensive_dd', order: 5, title: 'Comprehensive Due Diligence' },
      { key: 'contract_full', order: 6, title: 'Contract Prep, Negotiation & Advisory' },
      { key: 'transfer', order: 7, title: 'Land Transfer & Registration' },
      { key: 'instruments', order: 8, title: 'Drafting of Legal Instruments' },
      { key: 'advisory', order: 9, title: 'Legal Advisory & Ongoing Support' },
      { key: 'regulatory', order: 10, title: 'Regulatory Filings & Approvals' },
    ],

    steps: [
      {
        key: 'DD_1_ONBOARDING',
        order: 1,
        stageKey: 'onboarding',
        title: 'Client Onboarding & Consultation',
        actions: [
          'Open client file & register matter',
          'Conduct intake consultation',
          'Discuss objectives & transaction overview',
          'Collect initial documents from client',
          'Sign engagement letter',
          'Conflict check',
        ],
        outputs: [
          { key: 'engagement_letter', name: 'Signed engagement letter', required: true, category: 'Engagement' },
          { key: 'client_file_opened', name: 'Opened client file', required: true, category: 'Administration' },
          { key: 'project_plan', name: 'Project plan with agreed milestones', required: false, category: 'Planning' },
          { key: 'doc_receipt_ack', name: 'Document receipt acknowledgment', required: false, category: 'Administration' },
          { key: 'conflict_check', name: 'Conflict check accomplished', required: true, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'range', currency: 'RWF', min: 50000, max: 200000 },
        sla: { unit: 'hours', min: 4, max: 8, text: '4–8 hours' },
      },
      {
        key: 'DD_2_INITIAL_REVIEW',
        order: 2,
        stageKey: 'initial_review',
        title: 'Initial Review & Legal Assessment',
        actions: [
          'Review title deeds & cadastral maps',
          'Conduct Certificate of Title Search',
          'Verify ownership identity',
          'Issue preliminary legal risk advice',
        ],
        outputs: [
          { key: 'title_search_certificate', name: 'Title search certificate', required: true, category: 'Land' },
          { key: 'ownership_confirmation', name: 'Ownership confirmation letter', required: false, category: 'Land' },
          { key: 'risk_memo_prelim', name: 'Preliminary legal risk memo', required: false, category: 'Advice' },
        ],
        legalBasis: [{ text: 'N/A (included in consultation fee)' }],
        fee: { type: 'included', text: 'Included in consultation fee' },
        sla: { unit: 'hours', min: 4, max: 8, text: '4–8 hours' },
      },
      {
        key: 'DD_3_BASIC_DD',
        order: 3,
        stageKey: 'basic_dd',
        title: 'Basic Due Diligence',
        actions: [
          "Verify ownership & seller's right to transfer",
          'Check for major encumbrances or liens',
          'Review cadastral plan & confirm boundaries',
          'Conduct limited zoning & compliance check',
        ],
        outputs: [
          { key: 'basic_dd_report', name: 'Basic due diligence report', required: true, category: 'Due Diligence' },
          { key: 'encumbrances_summary', name: 'Encumbrance & liens summary', required: true, category: 'Due Diligence' },
          { key: 'boundary_note', name: 'Boundary confirmation note', required: false, category: 'Due Diligence' },
          { key: 'zoning_note', name: 'Zoning status note', required: false, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'text', text: '5,000,000 RWF plus fees calculated on capital according to proportions' },
        sla: { unit: 'hours', min: 24, max: 72, text: '24–72 hours' },
      },
      {
        key: 'DD_4_CONTRACT_BASIC',
        order: 4,
        stageKey: 'contract_basic',
        title: 'Contract Preparation & Advisory (Basic)',
        actions: ['Draft simple Sale-Purchase Agreement', 'Provide advice during transaction', 'Oversee signing and notarization'],
        outputs: [
          { key: 'spa_draft', name: 'Drafted Sale-Purchase Agreement document', required: true, category: 'Contract' },
          { key: 'transaction_advice', name: 'Legal advice/guidance during transaction', required: false, category: 'Advice' },
          { key: 'spa_signed_notarized', name: 'Signed and notarized Sale-Purchase Agreement', required: false, category: 'Contract' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'range', currency: 'RWF', min: 500000, max: 3000000 },
        sla: { unit: 'days', min: 0, max: 1, text: 'Same day' },
      },
      {
        key: 'DD_5_COMPREHENSIVE_DD',
        order: 5,
        stageKey: 'comprehensive_dd',
        title: 'Comprehensive Due Diligence',
        actions: [
          'Ownership & title verification (authentic title, history)',
          'Encumbrances & legal restrictions (bankruptcy, liens, mortgages, court cases)',
          'Land use & zoning compliance (master plan, expropriation risks)',
          'Environmental assessment (soil, wetlands, hazard/flood zones)',
          'Utilities & infrastructure (road, water, power, internet)',
          'Tax & financial obligations (tax history, lease payments, transfer taxes)',
          'Seller legitimacy & social risk (fraud check, disputes)',
          'Foreign ownership compliance (eligibility, conformity)',
        ],
        outputs: [
          { key: 'title_verification_report', name: 'Title Verification Report', required: true, category: 'Due Diligence' },
          { key: 'encumbrance_status_report', name: 'Encumbrance & Legal Status Report', required: true, category: 'Due Diligence' },
          { key: 'zoning_compliance_report', name: 'Zoning & Land Use Compliance Report', required: false, category: 'Compliance' },
          { key: 'environmental_risk_report', name: 'Environmental Risk Report', required: false, category: 'Risk' },
          { key: 'infrastructure_report', name: 'Infrastructure & Utilities Report', required: false, category: 'Utilities' },
          { key: 'tax_clearance_report', name: 'Tax & Financial Clearance Report', required: false, category: 'Tax' },
          { key: 'seller_verification_report', name: 'Seller Verification Report', required: false, category: 'Risk' },
          { key: 'foreign_compliance_report', name: 'Foreign Ownership Compliance Report', required: false, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'text', text: '5,000,000 RWF plus fees calculated on capital according to proportions' },
        sla: { unit: 'hours', min: 24, max: 72, text: '24–72 hours' },
      },
      {
        key: 'DD_6_CONTRACT_FULL',
        order: 6,
        stageKey: 'contract_full',
        title: 'Contract Preparation, Negotiation & Advisory',
        actions: [
          'Draft & review Sale-Purchase Agreement & Memorandum of Transfer',
          'Risk allocation schedules, warranties, indemnities, conditions precedent',
          'Negotiate balanced terms with counterparty',
          'Supervise contract signing & notarization',
        ],
        outputs: [
          { key: 'final_spa_transfer_docs', name: 'Finalized Sale-Purchase Agreement & Transfer Documents', required: true, category: 'Contract' },
          { key: 'risk_allocation_schedule', name: 'Risk Allocation Schedule', required: false, category: 'Contract' },
          { key: 'signed_notarized_agreement', name: 'Signed & notarized agreement', required: false, category: 'Contract' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'range', currency: 'RWF', min: 500000, max: 3000000 },
        sla: { unit: 'days', min: 5, max: 7, text: '5–7 working days' },
      },
      {
        key: 'DD_7_TRANSFER_REG',
        order: 7,
        stageKey: 'transfer',
        title: 'Land Transfer & Registration',
        actions: [
          'Guide transfer process',
          'Supervise notarization of transfer deed',
          'Arrange stamping & payment of duties',
          'Submit transfer via land portal',
          'Liaise with local decentralized & land office',
          'Obtain new land title',
          'SPV/nominee structuring (if needed)',
        ],
        outputs: [
          { key: 'notarized_transfer_deed', name: 'Notarized Transfer Deed', required: true, category: 'Transfer' },
          { key: 'portal_submission_confirmation', name: 'Transfer submission confirmation (Land Portal)', required: false, category: 'Transfer' },
          { key: 'new_land_title', name: 'New land title issued (buyer name)', required: false, category: 'Transfer' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 600000 },
        sla: { unit: 'hours', min: 3, max: 4, text: '3–4 hours' },
      },
      {
        key: 'DD_8_INSTRUMENTS',
        order: 8,
        stageKey: 'instruments',
        title: 'Drafting of Legal Instruments',
        actions: ['Draft Power of Attorney (if required)', 'Draft other instruments', 'Provide legal representation'],
        outputs: [
          { key: 'power_of_attorney', name: 'Power of Attorney (if required)', required: false, category: 'Instruments' },
          { key: 'board_resolutions', name: 'Board resolutions / undertakings', required: false, category: 'Instruments' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'text', text: '200,000 – 20,000,000 RWF' },
        sla: { unit: 'days', min: 0, max: 1, text: 'Same day' },
      },
      {
        key: 'DD_9_ADVISORY',
        order: 9,
        stageKey: 'advisory',
        title: 'Legal Advisory & Ongoing Support',
        actions: [
          'Advice on land/investment/contract/tax law approvals',
          'Labour & compliance guidance',
          'Tax advisory',
          'Risk management advice',
        ],
        outputs: [{ key: 'advisory_memo', name: 'Advisory memo / guidance delivered', required: false, category: 'Advice' }],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'text', text: '300,000 – 30,000,000 RWF' },
        sla: { unit: 'hours', min: 24, max: 72, text: '24–72 hours' },
      },
      {
        key: 'DD_10_REGULATORY',
        order: 10,
        stageKey: 'regulatory',
        title: 'Regulatory Filings & Approvals',
        actions: ['Obtain Conformity Letter', 'Secure District Confirmation', 'Obtain No-Objection Letters', 'Liaison with offices'],
        outputs: [
          { key: 'conformity_letter', name: 'Conformity letter', required: false, category: 'Regulatory' },
          { key: 'district_confirmation', name: 'District confirmation', required: false, category: 'Regulatory' },
          { key: 'no_objection_letters', name: 'Regulatory no-objection letters', required: false, category: 'Regulatory' },
        ],
        legalBasis: [{ text: 'N/A' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 600000 },
        sla: { unit: 'hours', min: 24, max: 48, text: '24–48 hours' },
      },
    ],
  });
};