import WorkflowTemplate from '../models/workflowTemplateModel';

export const seedForeignerLandAcquisitionTemplate = async () => {
  const name = 'Foreigner Acquiring Land in Rwanda';
  const version = 1;

  const template = {
    name,
    matterType: 'Foreigner Acquiring Land in Rwanda',
    caseType: 'Transactional Cases',
    version,
    active: true,

    stages: [
      { key: 'intake_eligibility', order: 1, title: 'Initial Client Intake & Eligibility Assessment' },
      { key: 'due_diligence', order: 2, title: 'Land Identification & Due Diligence' },
      { key: 'tenure_selection', order: 3, title: 'Tenure Selection' },
      { key: 'rdb_authority', order: 4, title: 'RDB / Authority Application & Competition Process' },
      { key: 'contract', order: 5, title: 'Contract Formation & Notarisation' },
      { key: 'registration', order: 6, title: 'Land Registration' },
      { key: 'post_registration', order: 7, title: 'Post-Registration Obligations & Compliance' },
      { key: 'renewal_disputes', order: 8, title: 'Lease Renewal, Transfer of Rights & Dispute Resolution' },
    ],

    steps: [
      {
        key: 'FLA_1_CLIENT_INTAKE',
        order: 1,
        stageKey: 'intake_eligibility',
        title: 'Client Intake',
        actions: ['Receive foreign client and conduct initial interview', 'Confirm foreign national status and nationality', 'Conduct conflict-of-interest check', 'Sign engagement letter'],
        outputs: [
          { key: 'instruction_letter', name: 'Client instruction letter', required: true, category: 'Intake' },
          { key: 'intake_form', name: 'Intake form', required: true, category: 'Intake' },
          { key: 'conflict_declaration', name: 'Conflict of Interest Declaration', required: true, category: 'Compliance' },
          { key: 'engagement_letter', name: 'Engagement letter', required: true, category: 'Engagement' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 1, 2 and 16' }],
        fee: { type: 'text', text: 'RWF 30,000 opening file - Art. 21 RBA Regulation' },
        sla: { unit: 'hours', min: 4, max: 8, text: 'Within 4-8 hours of initial contact' },
      },
      {
        key: 'FLA_2_ELIGIBILITY',
        order: 2,
        stageKey: 'intake_eligibility',
        title: 'Eligibility Assessment',
        actions: ['Determine whether client qualifies for emphyteutic lease or land concession', 'Confirm land is allocated for investment purposes only', 'Advise on no freehold for foreigners unless Presidential Order'],
        outputs: [
          { key: 'eligibility_opinion', name: 'Eligibility opinion note', required: true, category: 'Advice' },
          { key: 'tenure_summary', name: 'Summary of applicable tenure modality', required: true, category: 'Advice' },
          { key: 'client_advisory', name: 'Client advisory memo', required: true, category: 'Advice' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 6, 9 and 16' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 300000, text: 'Art. 22(1) RBA Regulation' },
        sla: { unit: 'days', min: 1, max: 3, text: 'Within 24-72 hours of instruction' },
      },
      {
        key: 'FLA_3_INVESTMENT_PURPOSE',
        order: 3,
        stageKey: 'intake_eligibility',
        title: 'Investment Purpose Verification',
        actions: ['Confirm acquisition is for investment purposes', 'Identify sector of investment', 'Draft written legal advice on applicable tenure type'],
        outputs: [
          { key: 'written_advice', name: 'Written legal advice', required: true, category: 'Advice' },
          { key: 'sector_confirmation', name: 'Investment sector confirmation note', required: true, category: 'Investment' },
          { key: 'referral_letter', name: 'Referral letter if needed', required: false, category: 'Investment' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 11, 12 and 16(2)' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 300000, text: 'Art. 22(1)' },
        sla: { unit: 'days', min: 1, max: 3, text: 'Within 24-72 hours of assessment' },
      },
      {
        key: 'FLA_4_LAND_SEARCH',
        order: 4,
        stageKey: 'due_diligence',
        title: 'Land Search & Verification',
        actions: ['Conduct land register search at RLMUA', 'Verify land title, boundaries and registered owner', 'Confirm land is not in public domain or protected swamp'],
        outputs: [
          { key: 'register_search', name: 'Land register search result', required: true, category: 'Land' },
          { key: 'certificate_copy', name: 'Certificate of land registration copy', required: true, category: 'Land' },
          { key: 'title_report', name: 'Land title verification report', required: true, category: 'Due Diligence' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 17, 18, 19, 20, 31 and 33' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 200000, text: 'Art. 22(2) RBA Regulation' },
        sla: { unit: 'days', min: 2, max: 5, text: 'Within 2-5 business days' },
      },
      {
        key: 'FLA_5_PHYSICAL_DD',
        order: 5,
        stageKey: 'due_diligence',
        title: 'Physical Due Diligence',
        actions: ['Engage licensed land surveyor to confirm boundaries', 'Conduct site visit and physical inspection', 'Verify compliance with Land Use Master Plan'],
        outputs: [
          { key: 'survey_report', name: 'Survey report', required: true, category: 'Survey' },
          { key: 'site_report', name: 'Site inspection report', required: true, category: 'Due Diligence' },
          { key: 'land_use_confirmation', name: 'Land use compliance confirmation', required: true, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 25, 54, 55, 61 and 85' }],
        fee: { type: 'range', currency: 'RWF', min: 50000, max: 150000, text: 'Art. 22(2)' },
        sla: { unit: 'days', min: 3, max: 5, text: 'Within 3-5 business days' },
      },
      {
        key: 'FLA_6_VALUATION',
        order: 6,
        stageKey: 'due_diligence',
        title: 'Land Valuation',
        actions: ['Engage licensed land valuer to assess market value', 'Obtain official valuation certificate', 'Review valuation for negotiation and stamp duty purposes'],
        outputs: [
          { key: 'valuation_report', name: 'Land valuation report', required: true, category: 'Valuation' },
          { key: 'valuation_certificate', name: 'Valuation certificate', required: true, category: 'Valuation' },
          { key: 'stamp_duty_estimate', name: 'Stamp duty estimate', required: false, category: 'Tax' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 25(3), 84; Law No. 016/2018' }],
        fee: { type: 'range', currency: 'RWF', min: 50000, max: 150000, text: 'Art. 22(2)' },
        sla: { unit: 'days', min: 3, max: 5, text: 'Within 3-5 business days' },
      },
      {
        key: 'FLA_7_EMPHYTEUTIC_LEASE',
        order: 7,
        stageKey: 'tenure_selection',
        title: 'Emphyteutic Lease',
        actions: ['Advise client on emphyteutic lease up to 99 years and renewal', 'Confirm client eligibility under Art. 16(1)(a)', 'Initiate application through competent authority'],
        outputs: [
          { key: 'lease_advisory', name: 'Client advisory on emphyteutic lease', required: true, category: 'Advice' },
          { key: 'eligibility_letter', name: 'Eligibility confirmation letter', required: true, category: 'Advice' },
          { key: 'lease_application', name: 'Lease application draft', required: false, category: 'Application' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 9, 10 and 16(1)(a)' }],
        fee: { type: 'range', currency: 'RWF', min: 200000, max: 500000, text: 'Art. 22(1) RBA Regulation' },
        sla: { unit: 'days', min: 3, max: 5, text: 'Within 3-5 business days of instruction' },
      },
      {
        key: 'FLA_8_CONCESSION',
        order: 8,
        stageKey: 'tenure_selection',
        title: 'Land Concession',
        actions: ['Advise on concession up to 49 years renewable by agreement', 'Confirm strategic investment sector', 'Prepare draft concession agreement outline'],
        outputs: [
          { key: 'concession_note', name: 'Concession advisory note', required: true, category: 'Advice' },
          { key: 'sector_memo', name: 'Investment sector classification memo', required: true, category: 'Investment' },
          { key: 'concession_outline', name: 'Draft concession agreement outline', required: false, category: 'Contract' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 11 and 16(1)(b)' }],
        fee: { type: 'range', currency: 'RWF', min: 200000, max: 500000, text: 'Art. 22(1)' },
        sla: { unit: 'days', min: 3, max: 5, text: 'Within 3-5 business days' },
      },
      {
        key: 'FLA_9_STATE_LEASE',
        order: 9,
        stageKey: 'tenure_selection',
        title: 'State Land Lease (Commercial Purposes)',
        actions: ['Advise on State land lease for commercial infrastructure up to 99 years', 'Confirm eligible commercial purpose'],
        outputs: [
          { key: 'state_lease_advisory', name: 'State land lease advisory', required: true, category: 'Advice' },
          { key: 'commercial_purpose', name: 'Eligible commercial purpose confirmation', required: true, category: 'Investment' },
          { key: 'lease_outline', name: 'Draft lease agreement outline', required: false, category: 'Contract' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Art. 12' }],
        fee: { type: 'range', currency: 'RWF', min: 200000, max: 500000, text: 'Art. 22(1)' },
        sla: { unit: 'days', min: 3, max: 5, text: 'Within 3-5 business days' },
      },
      {
        key: 'FLA_10_RDB',
        order: 10,
        stageKey: 'rdb_authority',
        title: 'Investment Registration with RDB',
        actions: ['Register investment with RDB', 'Obtain investment certificate or strategic investment status if applicable', 'Confirm sector eligibility'],
        outputs: [
          { key: 'rdb_certificate', name: 'RDB investment registration certificate', required: true, category: 'Investment' },
          { key: 'strategic_status', name: 'Strategic investment status letter', required: false, category: 'Investment' },
          { key: 'sector_eligibility', name: 'Sector eligibility confirmation', required: true, category: 'Investment' },
        ],
        legalBasis: [{ text: 'RDB Act No. 006/2015; Law No. 27/2021, Arts. 11(2) and 13' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 300000, text: 'Art. 22(1) RBA Regulation' },
        sla: { unit: 'days', min: 5, max: 10, text: 'Within 5-10 business days' },
      },
      {
        key: 'FLA_11_TENDER',
        order: 11,
        stageKey: 'rdb_authority',
        title: 'Competitive Tender Process',
        actions: ['Prepare bid documents for State land concession or lease tender', 'Submit approved business plan', 'Participate in selection or obtain Cabinet exemption'],
        outputs: [
          { key: 'bid_package', name: 'Bid submission package', required: false, category: 'Tender' },
          { key: 'business_plan', name: 'Approved business plan', required: false, category: 'Tender' },
          { key: 'tender_confirmation', name: 'Tender participation confirmation or Cabinet decision', required: false, category: 'Tender' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Art. 13' }],
        fee: { type: 'range', currency: 'RWF', min: 300000, max: 700000, text: 'Art. 22(1)' },
        sla: { unit: 'days', min: 30, max: 60, text: 'Subject to tender timelines, typically 30-60 days' },
      },
      {
        key: 'FLA_12_COMPLIANCE_REQUIREMENTS',
        order: 12,
        stageKey: 'rdb_authority',
        title: 'Compliance Requirements',
        actions: ['Review and accept compliance requirements for State land', 'Confirm obligations to use land per contract, business plan and laws'],
        outputs: [
          { key: 'compliance_checklist', name: 'Compliance checklist', required: true, category: 'Compliance' },
          { key: 'repossession_advisory', name: 'Client advisory on repossession risk', required: true, category: 'Advice' },
          { key: 'compliance_undertaking', name: 'Signed compliance undertaking', required: false, category: 'Compliance' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Art. 14; Prime Minister Order on modalities' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 200000, text: 'Art. 22(2)' },
        sla: { unit: 'days', min: 0, max: 1, text: 'Before signing any land contract' },
      },
      {
        key: 'FLA_13_CONTRACT_DRAFT',
        order: 13,
        stageKey: 'contract',
        title: 'Drafting the Land Contract',
        actions: ['Draft emphyteutic lease, concession or State land lease agreement', 'Ensure all registered title holders consent', 'Include purpose, term, renewal, obligations and restrictions'],
        outputs: [
          { key: 'draft_contract', name: 'Draft lease/concession agreement', required: true, category: 'Contract' },
          { key: 'owner_consents', name: 'Consent confirmation from all registered owners', required: true, category: 'Contract' },
          { key: 'notary_instruction', name: 'Instruction letter to notary', required: false, category: 'Notary' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 22, 23 and 26' }],
        fee: { type: 'range', currency: 'RWF', min: 300000, max: 1000000, text: 'Art. 26 RBA Regulation' },
        sla: { unit: 'days', min: 5, max: 7, text: 'Within 5-7 business days' },
      },
      {
        key: 'FLA_14_NOTARISATION',
        order: 14,
        stageKey: 'contract',
        title: 'Notarisation of Contract',
        actions: ['Submit signed contract to competent land notary', 'Use electronic contract with digital signatures if applicable', 'Ensure notary is recognised by Chief Registrar of Land Titles'],
        outputs: [
          { key: 'notarised_contract', name: 'Notarised lease/concession contract', required: true, category: 'Notary' },
          { key: 'digital_signature', name: 'Digital signature confirmation (if electronic)', required: false, category: 'Notary' },
          { key: 'notary_certification', name: 'Notary certification', required: true, category: 'Notary' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 15 and 23' }],
        fee: { type: 'included', text: 'Included in contract/notarial handling fees' },
        sla: { unit: 'days', min: 2, max: 5, text: 'Within 2-5 business days of draft approval' },
      },
      {
        key: 'FLA_15_VALIDITY',
        order: 15,
        stageKey: 'contract',
        title: 'Validity of Transfer',
        actions: ['Confirm contract is valid only upon registration in land register', 'Advise client not to use or pay for land until registration is complete', 'Proceed immediately to land registration'],
        outputs: [
          { key: 'validity_memo', name: 'Validity advisory memo', required: true, category: 'Advice' },
          { key: 'registration_checklist', name: 'Registration readiness checklist', required: true, category: 'Registration' },
          { key: 'registrar_file', name: 'File for submission to Registrar', required: true, category: 'Registration' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 17, 18 and 24' }],
        fee: { type: 'included', text: 'Included in registration fees' },
        sla: { unit: 'days', min: 0, max: 1, text: 'Immediately after notarisation' },
      },
      {
        key: 'FLA_16_REGISTRATION_APPLICATION',
        order: 16,
        stageKey: 'registration',
        title: 'Application for Registration',
        actions: ['File application with RLMUA / Registrar', 'Submit notarised contract, land title, identity documents and RDB certificate', 'Pay applicable registration fees and taxes'],
        outputs: [
          { key: 'registration_application', name: 'Registration application form', required: true, category: 'Registration' },
          { key: 'submission_receipt', name: 'Document submission receipt', required: true, category: 'Registration' },
          { key: 'fee_confirmation', name: 'Fee payment confirmation', required: true, category: 'Payment' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 15, 17 and 36; Law No. 016/2018' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 300000, text: 'Art. 22(1) RBA Regulation' },
        sla: { unit: 'days', min: 5, max: 10, text: 'Within 5-10 business days of notarisation' },
      },
      {
        key: 'FLA_17_CERTIFICATE',
        order: 17,
        stageKey: 'registration',
        title: 'Issuance of Land Certificate',
        actions: ['Receive Certificate of Land Registration', 'Verify names, land description, tenure type, term and boundaries', 'Confirm registration in Land Register'],
        outputs: [
          { key: 'land_certificate', name: 'Certificate of land registration', required: true, category: 'Registration' },
          { key: 'register_entry', name: 'Land register entry confirmation', required: true, category: 'Registration' },
          { key: 'verified_certificate', name: 'Verified certificate copy for client file', required: true, category: 'Registration' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 15, 18, 19 and 20' }],
        fee: { type: 'included', text: 'Included in registration process' },
        sla: { unit: 'days', min: 1, max: 10, text: 'Issued by Registrar after registration processing' },
      },
      {
        key: 'FLA_18_SUBLEASE',
        order: 18,
        stageKey: 'registration',
        title: 'Sub-Lease Registration (If Applicable)',
        actions: ['Ensure written sub-lease contract', 'Register sub-lease if term is 5 years or more', 'Advise sub-lessee cannot acquire prescription rights'],
        outputs: [
          { key: 'sublease_agreement', name: 'Sub-lease agreement (written)', required: false, category: 'Contract' },
          { key: 'sublease_registration', name: 'Sub-lease registration confirmation (if 5 years or more)', required: false, category: 'Registration' },
          { key: 'sublessee_advisory', name: 'Advisory to sub-lessee on prescription exclusion', required: false, category: 'Advice' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 26, 28 and 50(2)' }],
        fee: { type: 'range', currency: 'RWF', min: 50000, max: 150000, text: 'Art. 22(2)' },
        sla: { unit: 'days', min: 0, max: 10, text: 'Within 10 business days of sub-lease execution' },
      },
      {
        key: 'FLA_19_LAND_USE',
        order: 19,
        stageKey: 'post_registration',
        title: 'Land Use Obligations',
        actions: ['Advise client to protect, conserve and exploit land', 'Ensure productive use per intended purpose', 'Comply with Land Use and Development Master Plan'],
        outputs: [
          { key: 'land_use_checklist', name: 'Land use compliance checklist', required: false, category: 'Compliance' },
          { key: 'annual_land_use_plan', name: 'Annual land use plan', required: false, category: 'Compliance' },
          { key: 'productive_use_advisory', name: 'Client advisory on productive use obligation', required: false, category: 'Advice' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 44, 46, 55 and 61' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 200000, text: 'Art. 22(2) RBA Regulation' },
        sla: { unit: 'weeks', text: 'Ongoing from date of registration' },
      },
      {
        key: 'FLA_20_TAX',
        order: 20,
        stageKey: 'post_registration',
        title: 'Tax & Fee Obligations',
        actions: ['Register for land tax with RRA', 'Pay annual land tax and fees', 'Comply with withholding tax and income tax on rental income'],
        outputs: [
          { key: 'rra_land_tax', name: 'RRA land tax registration', required: false, category: 'Tax' },
          { key: 'tax_receipts', name: 'Annual land tax receipts', required: false, category: 'Tax' },
          { key: 'tax_certificate', name: 'Tax compliance certificate', required: false, category: 'Tax' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Art. 48; Law No. 016/2018; Income Tax Law No. 32/2023' }],
        fee: { type: 'text', text: 'Per RRA tax schedule (annual)' },
        sla: { unit: 'weeks', text: 'Annually per RRA deadlines' },
      },
      {
        key: 'FLA_21_RESTRICTIONS',
        order: 21,
        stageKey: 'post_registration',
        title: 'Restrictions & Prohibitions Monitoring',
        actions: ['Remind client no sale or transfer of land under concession / State lease', 'Confirm change of investment activity requires prior approval', 'Advise State may terminate contract with 90-day notice for non-compliance'],
        outputs: [
          { key: 'compliance_advisory', name: 'Client compliance advisory', required: false, category: 'Advice' },
          { key: 'annual_review', name: 'Annual compliance review report', required: false, category: 'Compliance' },
          { key: 'change_application', name: 'Change-of-use application (if needed)', required: false, category: 'Application' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 11, 12, 14 and 49' }],
        fee: { type: 'range', currency: 'RWF', min: 100000, max: 200000, text: 'Art. 22(2)' },
        sla: { unit: 'weeks', text: 'Ongoing; review annually' },
      },
      {
        key: 'FLA_22_RENEWAL',
        order: 22,
        stageKey: 'renewal_disputes',
        title: 'Lease Renewal',
        actions: ['Monitor approaching end of lease or concession term', 'Advise foreigners must negotiate renewal for emphyteutic lease', 'Prepare renewal application and investment track record documents'],
        outputs: [
          { key: 'renewal_application', name: 'Lease renewal application', required: false, category: 'Renewal' },
          { key: 'investment_report', name: 'Investment performance report', required: false, category: 'Renewal' },
          { key: 'renewed_agreement', name: 'Renewed lease agreement', required: false, category: 'Renewal' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 10, 11 and 12' }],
        fee: { type: 'range', currency: 'RWF', min: 200000, max: 500000, text: 'Art. 22(1) RBA Regulation' },
        sla: { unit: 'weeks', text: 'At least 6 months before expiry' },
      },
      {
        key: 'FLA_23_TRANSFER_RIGHTS',
        order: 23,
        stageKey: 'renewal_disputes',
        title: 'Transfer / Mortgage of Concession Rights',
        actions: ['Advise on right to sell, transfer or mortgage improvements/property on concession land', 'Draft and notarize transfer of concession rights agreement', 'Register transfer of rights with Registrar of Land Titles'],
        outputs: [
          { key: 'rights_transfer_agreement', name: 'Transfer of concession rights agreement', required: false, category: 'Contract' },
          { key: 'notarised_transfer', name: 'Notarised transfer contract', required: false, category: 'Notary' },
          { key: 'updated_register_entry', name: 'Updated land register entry', required: false, category: 'Registration' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 11(7), 21, 23 and 24' }],
        fee: { type: 'range', currency: 'RWF', min: 300000, max: 1000000, text: 'Art. 26' },
        sla: { unit: 'days', min: 0, max: 10, text: 'Within 10 business days' },
      },
      {
        key: 'FLA_24_DISPUTE',
        order: 24,
        stageKey: 'renewal_disputes',
        title: 'Dispute Resolution',
        actions: ['File boundary or registration dispute with District or City of Kigali', 'Appeal to RLMUA within 30 days if needed', 'Lodge or cancel caveat with Registrar'],
        outputs: [
          { key: 'dispute_application', name: 'Dispute application (written)', required: false, category: 'Dispute' },
          { key: 'rlmua_appeal', name: 'RLMUA appeal submission', required: false, category: 'Dispute' },
          { key: 'caveat_application', name: 'Caveat application / cancellation letter', required: false, category: 'Dispute' },
          { key: 'court_filing', name: 'Court filing (if escalated)', required: false, category: 'Dispute' },
        ],
        legalBasis: [{ text: 'Law No. 27/2021, Arts. 73 and 74' }],
        fee: { type: 'range', currency: 'RWF', min: 200000, max: 1000000, text: 'Art. 26 and Art. 33 RBA' },
        sla: { unit: 'days', min: 30, max: 45, text: 'District: 30 days; RLMUA: 45 days; Court: 30 days from RLMUA decision' },
      },
    ],
  };

  await WorkflowTemplate.updateMany(
    { name, version: { $lt: version } },
    { $set: { active: false } }
  );

  return WorkflowTemplate.findOneAndUpdate(
    { name, version },
    { $set: template },
    { returnDocument: 'after', upsert: true, setDefaultsOnInsert: true }
  );
};
