import 'dotenv/config';
import connectDB from '../config/db';
import WorkflowTemplate from '../models/workflowTemplateModel';
import { normalizeTemplateActionText } from '../utils/workflowText';

/**
 * One-time data cleanup: removes manually-entered Key Action numbering (e.g.
 * "1. Assess facts..." → "Assess facts...") that may have been stored as part
 * of the Key Action text by older versions of the workflow editor.
 *
 * Display numbering is always generated by the application, so clean stored
 * data is enough. Run with: npm run normalize:workflows
 */
const run = async () => {
  await connectDB();

  console.log('Scanning workflow templates for manually entered Key Action numbering...');

  const templates = await WorkflowTemplate.find({}).lean();
  let normalizedCount = 0;
  let actionCount = 0;

  for (const template of templates) {
    const originalSteps = JSON.stringify((template as any).steps || []);
    const normalized = normalizeTemplateActionText(template as any);
    const cleanSteps = JSON.stringify(normalized.steps || []);

    if (originalSteps !== cleanSteps) {
      await WorkflowTemplate.updateOne({ _id: (template as any)._id }, { $set: { steps: normalized.steps } });
      normalizedCount += 1;
      actionCount += (normalized.steps || []).reduce(
        (count: number, step: any) => count + (Array.isArray(step?.actions) ? step.actions.length : 0),
        0
      );
      console.log(
        `  - ${String((template as any).name || 'Untitled')} (${String((template as any).matterType || '')}) — actions normalized`
      );
    }
  }

  console.log(`Done. Normalized ${normalizedCount} template(s), covering ${actionCount} Key Action(s).`);
  console.log('No manually entered numbering remains in the stored Key Action text.');
  process.exit(0);
};

run().catch((err) => {
  console.error('Script failed:', err);
  process.exit(1);
});
